name: PhotoIngest
options:
  bundleIdPrefix: com.northwoods
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  PhotoIngest:
    type: application
    platform: macOS
    sources:
      - path: PhotoIngest
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.northwoods.PhotoIngest
        PRODUCT_NAME: "Photo Ingest"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: PhotoIngest/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: PhotoIngest/Resources/PhotoIngest.entitlements
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        ENABLE_HARDENED_RUNTIME: true
        ENABLE_APP_SANDBOX: NO
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: true
